# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle
on:
  push:
    branches:
#      - main
      - develop
      - feature
      - hotfix
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      PASETO_ALGORITHM: ${{ secrets.PASETO_ALGORITHM }}
      PASETO_AUDIENCE: ${{ secrets.PASETO_AUDIENCE }}
      PASETO_ISSUER: ${{ secrets.PASETO_ISSUER }}
      PASETO_KEY_ID: ${{ secrets.PASETO_KEY_ID }}
      PASETO_PRIVATE_KEY: ${{ secrets.PASETO_PRIVATE_KEY }}
      PASETO_PUBLIC_KEY: ${{ secrets.PASETO_PUBLIC_KEY }}
      PASETO_TOKEN_ID: ${{ secrets.PASETO_TOKEN_ID }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
